### ISSUE TITLE
error

### ISSUE THREAD

**Issue by mainantikus** [foxer666/node-multi-hashing#2]
Hi. Thank for the great project. I am using UNOMP now and try to use your project for Lyra2z algo. 

I found the following error. I check the init.js file but the problem still unsolved. Please kindly help me. 
thanks

 
let cliHost = '';
        ^^^^^^^
SyntaxError: Unexpected identifier
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:902:3

**Comment by devnull-ed** [comment]
Node v8.0.x is required
